[HPC]
host_name = YOUR_HPC_HOST
user_name = YOUR_USERNAME
# PW Authentication Method
auth_method = password
password = YOUR_PASSWORD
# Alternative KEY authentication method
auth_method = key
private_key_path = C:/path/to/private_key.pem