run:
	@echo "OMP_NUM_THREADS=$$OMP_NUM_THREADS"
	@echo "BDM_NUM_THREADS=$$BDM_NUM_THREADS"
	@echo "VECLIB_MAXIMUM_THREADS=$$VECLIB_MAXIMUM_THREADS"
	../../build/./ABM4bio input.csv 1234
clean:
	rm -rf results
